# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c36e92cbe9d5e3c513b7f732f3cd50501a485361b81cb6f7ea1b424ef9bff794089fba19269414f83b066270c692cff9d3433371d5cf97f9db60c42b1ddaa4f

test:
  secret_key_base: ad786040629b513cf1ea5880ae5f7ec4543e8bcb875eb88d96ac7527c71e47e10fe222ada785d098d68173d5707aeb1522b8e62cc71e38d6f4fcbee2cbe031a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
